# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Zynq_Book/DA2PmodJE.xdc

# Block Designs: bd/zybo_with_pmodda2/zybo_with_pmodda2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_with_pmodda2 || ORIG_REF_NAME==zybo_with_pmodda2} -quiet] -quiet

# IP: bd/zybo_with_pmodda2/ip/zybo_with_pmodda2_processing_system7_0_0/zybo_with_pmodda2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_with_pmodda2_processing_system7_0_0 || ORIG_REF_NAME==zybo_with_pmodda2_processing_system7_0_0} -quiet] -quiet

# IP: bd/zybo_with_pmodda2/ip/zybo_with_pmodda2_DA2Pmod_0_0/zybo_with_pmodda2_DA2Pmod_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_with_pmodda2_DA2Pmod_0_0 || ORIG_REF_NAME==zybo_with_pmodda2_DA2Pmod_0_0} -quiet] -quiet

# IP: bd/zybo_with_pmodda2/ip/zybo_with_pmodda2_axi_gpio_0_0/zybo_with_pmodda2_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_with_pmodda2_axi_gpio_0_0 || ORIG_REF_NAME==zybo_with_pmodda2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zybo_with_pmodda2/ip/zybo_with_pmodda2_xbar_0/zybo_with_pmodda2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_with_pmodda2_xbar_0 || ORIG_REF_NAME==zybo_with_pmodda2_xbar_0} -quiet] -quiet

# IP: bd/zybo_with_pmodda2/ip/zybo_with_pmodda2_auto_pc_0/zybo_with_pmodda2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_with_pmodda2_auto_pc_0 || ORIG_REF_NAME==zybo_with_pmodda2_auto_pc_0} -quiet] -quiet

# IP: bd/zybo_with_pmodda2/ip/zybo_with_pmodda2_ps7_0_axi_periph_0/zybo_with_pmodda2_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_with_pmodda2_ps7_0_axi_periph_0 || ORIG_REF_NAME==zybo_with_pmodda2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zybo_with_pmodda2/ip/zybo_with_pmodda2_rst_ps7_0_100M_0/zybo_with_pmodda2_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_with_pmodda2_rst_ps7_0_100M_0 || ORIG_REF_NAME==zybo_with_pmodda2_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/zybo_with_pmodda2/zybo_with_pmodda2_ooc.xdc
